name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main
  # Allow manual runs
  workflow_dispatch: {}
  # Allow external repo (submodule) to trigger this via repository_dispatch
  repository_dispatch:
    types: [content_updated]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for git info
          submodules: recursive # Pull submodules
          # Allow using a dedicated PAT in SUBMODULES_TOKEN, but fall back to the default GITHUB_TOKEN
          token: ${{ secrets.SUBMODULES_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Update submodules to latest tracked branches
        run: |
          git submodule sync --recursive
          git submodule update --init --remote --recursive
      - name: Install Dependencies
        run: npm ci
      - name: Init bibliography frontmatter
        run: node scripts/init-bibliography-frontmatter.js
      - name: Generate Bibliography backlinks section (non-destructive)
        run: node scripts/generate-bibliography-backlinks.js
      - name: Show changed files (for CI debug)
        run: |
          echo "Files changed by scripts:"
          git status --porcelain || true
          git --no-pager diff --name-only || true
      - name: Build Quartz
        run: npx quartz build
      - name: List public directory (for CI debug)
        run: |
          echo "Public dir listing:"
          ls -la public || true
          ls -R public | sed -n '1,200p' || true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      # set the environment URL to the pages deployment URL
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
